[package]
name = "c_mine"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.95", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0.92"
serde_json = { version = "1.0.135" }
serde = { version = "1.0.217", features = ["derive"] }
