[package]
name = "tag_structs_gen"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
ringhopper-definitions = { git = "https://github.com/FishAndRips/ringhopper.git", rev = "032f0d38e5378caa26d33be135f65352a18afa6b" }
